import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/Header/Header';
import NextAuthProvider from './components/Provider/NextAuthProvider';
import ReduxProvider from './components/Provider/ReduxProvider';
import Portal from './(ecommerce)/cart/components/CartDrawerPortal';
import CartDrawer from './(ecommerce)/cart/components/CartDrawer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextAuthProvider>
					<ReduxProvider>
						<Header />
						{children}
					</ReduxProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
